"""Cria a tabela de usuarios

Revision ID: cf0fa169a6de
Revises: 
Create Date: 2025-10-04 14:27:11.724887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf0fa169a6de'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome_completo', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('celular', sa.String(length=15), nullable=False),
    sa.Column('perfil', sa.Enum('AGRICULTOR', 'INVESTIDOR', 'ADMIN', name='perfilenum'), nullable=False),
    sa.Column('status_kyc', sa.Enum('PENDENTE', 'VERIFICADO', 'REPROVADO', 'ANALISE_MANUAL', name='statuskycenum'), nullable=False),
    sa.Column('telegram_user_id', sa.String(length=255), nullable=True),
    sa.Column('telegram_vinculado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_user_id')
    )
    op.create_index(op.f('ix_usuarios_cpf'), 'usuarios', ['cpf'], unique=True)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_cpf'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
